import { GoogleSpreadsheet } from 'google-spreadsheet';
import { JWT } from 'google-auth-library';


// Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
const serviceAccountAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: `george-wedenin-gmail-com@reff2-402412.iam.gserviceaccount.com`,
  key: `-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCqUfq6zZ6lp34I\nmfSsUgrKCzW5KrOwzaJA2RWkWk2K5qVCloS8cUBIishnJC8k+fQ1T3fVe0vb7POt\nw/I3keRknqqY0XDI+0SYDSR62/+fO6yCYlH1g+UXqOrqbiMUroIRXVcFV593j3wy\nd07aAxamFTZmIsPj1qMEmLpmrcxi6q+1iJQNIYKSEei4F4Pc0M3ruyuRttM+t2mY\nxMBia5wuRWXAPPE8K70/FyT2yI1THXdaWEaWd3XttvTfYXl92kaJTtcFMDsUjvhm\nJm/PxmAc8vO2neOTLM7Nsv6A9fPhd2GUHa1AjlIs4dUad+cnB3aAxNVLbt5iB7V3\nm6aiF/h/AgMBAAECggEAOh8stWeqznP4Zf4HyXBb3zPxGuXQGTMrPf72zDXGxXJN\nDgqodFgfbEHz/oKSFge4RyL9zVu8eOoFBBTciQsfyhh9NhYu618Xut2tR8Hgmxm1\nlm7v8h0W5jqOI/7+uLWOjFdydU/ACwBrjRs6zNoF9hpCDJurhoo96jkmTxjbKRvH\nvf+3YtkL64VS2Ip8kFWzhVFZqWEPx+aJPv//EkLvHRMGjimqHRI74wB8ywTQOUax\nuD0kGiZS58KjrsArpbpT/Y/O9DGTbRAhibxZFSZIRjocYcggjShAqHgsyVh/AVVE\nB+J79pBDPSRTSZf2Kq6zebTV6aowMpS4+qDpQV3NXQKBgQDae9xo+5G5eFqttjXY\n1PBMAOCfe4nKonP/dQf6sipRm7uy5aa9lnijiVtaR0sjDx1WCwXo6W1oYPJkNH8l\nQZK/GV7zpAicv2vo2OV1o4C98yJKOIT05Qbff23QGGdLCkU6VSFrJB+tzeC8YPZu\nnG5etKRmQdpmRtPi7B0kJYldWwKBgQDHkO/gebFz9vpYFtqTXeJxkj8FXh2uh+s9\nKMnQn3T5gbchEP2NCxuXnA3mvz6917/4qdC45yTE2FmXK6ZcYv4SsBHPc2UOrjKM\nB9OWvEGKyIfh9Gef6vvmGxOkiFSBl39hTsmS7hZsraATNsaVSE5PTbSk9/ZaAQlB\n1N/k2cdGrQKBgQCnsAEPImZKL7GJOhxB+80iyFmejjbHq7/UBYLGSxBn6ls5h0Fe\nqaqV+cp/k9B7bBJcA8HZba9nOWFQv2oGsjlrKpHR9cgWZmTwJeiXTZJ2N7HNvWtu\neom36BnkaZZ95bgUeVpY3TTjNOyUKOd7Jd0gGw1C3rA9Z4cg14/WOmkfmQKBgQDE\nBxuJfSARD/4yvygu7166PnSHGj6/rKUmq0UqFye42nD/GwhkHhAZaWHCUgMYSbA5\nWt06c1oLvZSrSGYeg+KcirTD+M7Aj9347MsrWnprD7Vh/0g2roSHL/uod33C2gR2\nmgSovhPq5tXBaeHAy4iYn3SdQzCKkk/8iVTwH/d99QKBgQCPMohHGwoJRremi6CU\nZr+9EM3mB4IbnhN6O3kZBBamrQ0sYrN38fSaT6I/oeH+/PXIRuhgV35j9NZxc24H\n8gLDZn7ocUySEuvdpE2F9vf1CNaW3lxN5xNbUNAKDznWx6UBkZAw1aXTv3npRZn6\nw9pIMWrdtNzdphIoCSGw15o6ZQ==\n-----END PRIVATE KEY-----\n`,
  scopes: [
    'https://www.googleapis.com/auth/spreadsheets',
  ],
});

const doc = new GoogleSpreadsheet('11IGd5WV96ziBRZb_w9I9tn0AmtGZ6EjgA8i3N7R-OTA', serviceAccountAuth);

await doc.loadInfo(); // loads document properties and worksheets
console.log(doc.title);
await doc.updateProperties({ title: 'renamed doc' });

const sheet = doc.sheetsByIndex[0]; // or use `doc.sheetsById[id]` or `doc.sheetsByTitle[title]`
console.log(sheet.title);
console.log(sheet.rowCount);

// adding / removing sheets
const newSheet = await doc.addSheet({ title: 'another sheet' });
await newSheet.delete();